name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-22.04
    steps:
      - name: print greeting
        run: |
          echo "Hello World"
          echo "I am running my first GitHub Action!"
      - name: print goodbye
        run: echo "Done - bye!"
